data = {
    "user": [
      {
        chineseName:"黃育強",
        englishName:"Ray wong",
        studentID:"DB726106",
        status:"會長",
      },
      {
        chineseName: "张行健",
        englishName: "Christ Zhang",
        studentID: "DC027486",
        status: "學會會員",
    },
    {
        chineseName: "区国豪",
        englishName: "ouguohao",
        studentID: "DC026166",
        status: "學會會員",
    },
    {
        chineseName: "黃昊泓",
        englishName: "Wong Hou Wang",
        studentID: "DC026962",
        status: "學會會員",
    },
    {
        chineseName: "鍾家鴻",
        englishName: "Chong Ka Hong",
        studentID: "DC025512",
        status: "學會會員",
    },
    {
        chineseName: "何頌文",
        englishName: "Ho chong man",
        studentID: "DC026754",
        status: "學會會員",
    },
    {
        chineseName: "劉偉卓",
        englishName: "LaoWaiCheok ",
        studentID: "DC025992",
        status: "學會會員(未付費)",
    },
    {
        chineseName: "黃德裕",
        englishName: "Wong Tak U",
        studentID: "DC026727",
        status: "學會會員(未付費)",
    },
    {
        chineseName: "何鈺祺",
        englishName: "Ho Iok Kei",
        studentID: "DC026175",
        status: "學會會員(未付費)",
    },
    {
        chineseName: "薛蓓琳",
        englishName: "Nancy",
        studentID: "DC027232",
        status: "學會會員(未付費)",
    },
    {
        chineseName: "邝楚丰",
        englishName: "kuangchufeng",
        studentID: "DC028248",
        status: "學會會員(未付費)",
    },
    {
        chineseName: "黄少行",
        englishName: "huangshaoxing",
        studentID: "DC026709",
        status: "學會會員",
    },
    {
        chineseName: "黃心妍",
        englishName: "Wong Sam In",
        studentID: "DC025132",
        status: "學會會員",
    },
    {
        chineseName: "覃潔儀",
        englishName: "CHAM KIT I",
        studentID: "DC026081",
        status: "被選中的小朋友",
    },
    {
        chineseName: "梁浩銘",
        englishName: "Leong Hou Meng",
        studentID: "DC025784",
        status: "學會會員",
    },
    {
        chineseName: "司徒偉捷",
        englishName: "Si Tou Wai Chit",
        studentID: "DC025642",
        status: "學會會員",
    },
    {
        chineseName: "李浚軒",
        englishName: "Marco Lei Chon Hin",
        studentID: "DC026736",
        status: "學會會員",
    },
    {
        chineseName: "譚芯妍",
        englishName: "TAM SAM IN",
        studentID: "DC026271",
        status: "學會會員",
    },
    {
        chineseName: "黃駿賢",
        englishName: "Wong Chon In",
        studentID: "DC026679",
        status: "學會會員",
    },
    {
        chineseName: "何凱城",
        englishName: "HO HOI SENG",
        studentID: "BC001082",
        status: "學會會員(未付費)",
    },
    {
        chineseName: "王琛",
        englishName: "Wong Sam",
        studentID: "DC025965",
        status: "學會會員",
    },
    {
        chineseName: "陳遠樂",
        englishName: "CHEN UN LOK",
        studentID: "DC026404",
        status: "學會會員",
    },
    {
        chineseName: "李若璇",
        englishName: "Louise",
        studentID: "DC027534",
        status: "學會會員(未付費)",
    },
    {
        chineseName: "陈朱玄",
        englishName: "CHENZHUXUAN",
        studentID: "DC028058",
        status: "學會會員",
    },
    {
        chineseName: "鍾海欣",
        englishName: "Chong Hoi Ian",
        studentID: "DC026697",
        status: "學會會員",
    },
    {
        chineseName: "高健竣",
        englishName: "KOU KIN CHON",
        studentID: "DC025244",
        status: "學會會員(未付費)",
    },
    {
        chineseName: "盧嘉豪",
        englishName: "LOU KA HOU",
        studentID: "DC026205",
        status: "學會會員(未付費)",
    },
    {
        chineseName: "何世杰",
        englishName: "He Shijie",
        studentID: "DC027241",
        status: "學會會員(未付費)",
    },
    {
        chineseName: "林彬琦",
        englishName: "Jason Lam",
        studentID: "DC025663",
        status: "學會會員",
    },
    {
        chineseName: "梁立",
        englishName: "LiangLi",
        studentID: "DC025880",
        status: "學會會員(未付費)",
    },
    {
        chineseName: "黃偉權",
        englishName: "WONG WAI KUN",
        studentID: "DC026139",
        status: "學會會員",
    },
    {
        chineseName: "张华康",
        englishName: "ZHANG Huakang",
        studentID: "DB927606",
        status: "學會會員(未付費)",
    },
    {
        chineseName: "周俊宇",
        englishName: "Zhou Jun Yu",
        studentID: "DB928452",
        status: "學會會員",
    },
    {
        chineseName: "張梓軒",
        englishName: "cheong chi hin",
        studentID: "DB925201",
        status: "學會會員",
    },
    {
        chineseName: "謝子亮",
        englishName: "Tse Tsz Leong",
        studentID: "DB927141",
        status: "學會會員",
    },
    {
        chineseName: "張誠尉",
        englishName: "Cheong seng wai",
        studentID: "DB926446",
        status: "學會會員",
    },
    {
        chineseName: "朱家成",
        englishName: "Chu Ka Seng",
        studentID: "DB926473",
        status: "學會會員",
    },
    {
        chineseName: "王锦涛",
        englishName: "SAM",
        studentID: "DB827211",
        status: "學會會員",
    },
    {
        chineseName: "张逸腾",
        englishName: "CHEONG IAT TANG",
        studentID: "DB926808",
        status: "學會會員",
    },
    {
        chineseName: "廖振宏",
        englishName: "LIO CHAN WANG",
        studentID: "DB927045",
        status: "學會會員",
    },
    {
        chineseName: "张嘉晋",
        englishName: "Onyenwe",
        studentID: "DB928120",
        status: "學會會員",
    },
    {
        chineseName: "鄭志豪",
        englishName: "Chang Chi Hou",
        studentID: "DB927150",
        status: "學會會員",
    },
    {
        chineseName: "羅詠霖",
        englishName: "Lo Weng Lam",
        studentID: "DB926778",
        status: "學會會員",
    },
    {
        chineseName: "廖曉朗",
        englishName: "LIO HIO LONG",
        studentID: "DB926428",
        status: "學會會員",
    },
    {
        chineseName: "杨祺豪",
        englishName: "YANG QIHAO",
        studentID: "DB927072",
        status: "學會會員",
    },
    {
        chineseName: "劉耀康",
        englishName: "Lao Io Hong",
        studentID: "DB927036",
        status: "學會會員",
    },
    {
        chineseName: "鄧澤賢",
        englishName: "TANG CHAK IN",
        studentID: "DB927217",
        status: "學會會員",
    },
    {
        chineseName: "李嘉盛",
        englishName: "Coel Lee",
        studentID: "DB927651",
        status: "學會會員",
    },
    {
        chineseName: "邱宗豪",
        englishName: "Tony",
        studentID: "DB927178",
        status: "學會會員",
    },
    {
        chineseName: "江朝宇",
        englishName: "Keith",
        studentID: "DB927938",
        status: "學會會員",
    },
    {
        chineseName: "林美伶",
        englishName: "LIN MEI LING",
        studentID: "DB925705",
        status: "學會會員",
    },
    {
        chineseName: "陳紜峰",
        englishName: "CHAN WAN FONG",
        studentID: "DB925838",
        status: "學會會員",
    },
    {
        chineseName: "高靜怡",
        englishName: "KOU CHENG I",
        studentID: "DB927425",
        status: "學會會員",
    },
    {
        chineseName: "王博宇",
        englishName: "Wang boyu",
        studentID: "DB928232",
        status: "學會會員",
    },
    {
        chineseName: "譚凱竣",
        englishName: "Tam Hoi Chon",
        studentID: "DB925542",
        status: "學會會員",
    },
    {
        chineseName: "歐陽堅程",
        englishName: "AO IEONG KIN CHENG",
        studentID: "DB925023",
        status: "學會會員",
    },
    {
        chineseName: "張峻軒",
        englishName: "CHEONG CHON HIN",
        studentID: "DB925943",
        status: "學會會員",
    },
    {
        chineseName: "周濟程",
        englishName: "Rupter",
        studentID: "DB927793",
        status: "學會會員",
    },
    {
        chineseName: "卢莹茜",
        englishName: "Yuki",
        studentID: "DB928148",
        status: "學會會員",
    },
    {
        chineseName: "李昊炫",
        englishName: "Lei Hou Un",
        studentID: "DB926256",
        status: "學會會員",
    },
    {
        chineseName: "叢玉章",
        englishName: "CONG YUZHANG",
        studentID: "BB807213",
        status: "學會會員",
    },
    {
        chineseName: "胡文進",
        englishName: "WU MAN CHON",
        studentID: "DB927262",
        status: "學會會員",
    },
    {
        chineseName: "高進業",
        englishName: "Kou Chon Ip",
        studentID: "DB927292",
        status: "學會會員",
    },
    {
        chineseName: "柯思云",
        englishName: "Ke, Siyun",
        studentID: "DB927871",
        status: "學會會員",
    },
    {
        chineseName: "杨典儒",
        englishName: "YANGDIANRU",
        studentID: "DB926141",
        status: "學會會員",
    },
    {
        chineseName: "李永杰",
        englishName: "Lei Weng Kit ",
        studentID: "DB926986",
        status: "學會會員",
    },
    {
        chineseName: "何浩坤",
        englishName: "Tony",
        studentID: "DB928063",
        status: "學會會員",
    },
    {
        chineseName: "周永健",
        englishName: "CHAO WENG KIN",
        studentID: "DB927132",
        status: "學會會員",
    },
    {
        chineseName: "陳梓泳",
        englishName: "Chan Chi Weng",
        studentID: "DB926002",
        status: "學會會員",
    },
    {
        chineseName: "王博宇",
        englishName: "Wang boyu",
        studentID: "DB928232",
        status: "學會會員",
    },
    {
        chineseName: "李嘉盛",
        englishName: "Coel Lee",
        studentID: "DB927651",
        status: "學會會員",
    },
    {
        chineseName: "方博诣",
        englishName: "FONG POK NGAI",
        studentID: "DB925343",
        status: "學會會員",
    },
    {
        chineseName: "蘇澤浩",
        englishName: "SOU CHAK HOU",
        studentID: "DB926977",
        status: "學會會員",
    },
    {
        chineseName: "馬家康",
        englishName: "MA Ka Hong ",
        studentID: "DB926741",
        status: "學會會員",
    },
    {
        chineseName: "譚樟健",
        englishName: "Tam Chi Kin",
        studentID: "DB927452",
        status: "學會會員",
    },
    {
        chineseName: "劉偉嶔",
        englishName: "Wesley",
        studentID: "DB927377",
        status: "學會會員",
    },
    {
        chineseName: "謝子恆",
        englishName: "CHE CHI HANG ",
        studentID: "DB926533",
        status: "學會會員",
    },
    {
        chineseName: "李嘉林",
        englishName: "Eric Cartman",
        studentID: "DB925922",
        status: "學會會員",
    },
    {
        chineseName: "區健聰",
        englishName: "Au Kin Chong",
        studentID: "DB926011",
        status: "學會會員",
    },
    {
        chineseName: "劉紫恩",
        englishName: "LAO CHI IAN",
        studentID: "DB926105",
        status: "學會會員",
    },
    {
        chineseName: "劉毓棋",
        englishName: "Liu yuqi",
        studentID: "DB926171",
        status: "學會會員",
    },
    {
        chineseName: "許耀昌",
        englishName: "HOI IO CHEONG",
        studentID: "DB925117",
        status: "學會會員",
    },
    {
        chineseName: "陳美燕",
        englishName: "Chan Mei In",
        studentID: "DB925382",
        status: "學會會員",
    },
    {
        chineseName: "李晴雯",
        englishName: "LI CHENG MAN",
        studentID: "DB925078",
        status: "學會會員",
    },
    {
        chineseName: "黎凱琳",
        englishName: "LAI HOI LAM",
        studentID: "DB927169",
        status: "學會會員",
    },
    {
        chineseName: "黃峻彬",
        englishName: "Pascal",
        studentID: "DB926940",
        status: "學會會員",
    },
    {
        chineseName: "黃峻彬",
        englishName: "Pascal",
        studentID: "DB926940",
        status: "學會會員",
    },
    {
        chineseName: "蔡景亮",
        englishName: "keng leong CHOI",
        studentID: "DB925989",
        status: "學會會員",
    },
    {
        chineseName: "蘇澤浩",
        englishName: "SOU CHAK HOU",
        studentID: "DB926977",
        status: "學會會員",
    },
    {
        chineseName: "李鴻鍇",
        englishName: "Li Hung Kai ",
        studentID: "DB726362",
        status: "學會會員",
    },
    {
        chineseName: "陈泓彬",
        englishName: "CHEN WANGPAN",
        studentID: "BB901621",
        status: "學會會員",
    },
    {
        chineseName: "钱诗云",
        englishName: "QIAN SHIYUN",
        studentID: "SB824075",
        status: "學會會員",
    },
    {
        chineseName: "翟婉冰",
        englishName: "CHAK YUEN PING",
        studentID: "AB815682",
        status: "學會會員",
    },
    {
        chineseName: "宣磊",
        englishName: "XUAN LEI",
        studentID: "MB954325",
        status: "學會會員",
    },
    {
        chineseName: "陈少庭",
        englishName: "Nico",
        studentID: "SB923008",
        status: "學會會員",
    },
    {
        chineseName: "邰利鑫",
        englishName: "Tai lixin",
        studentID: "YB976441",
        status: "學會會員",
    },
    {
        chineseName: "刘云霄",
        englishName: "LIU YUNXIAO",
        studentID: "DB928374",
        status: "學會會員",
    },
    {
        chineseName: "王星宇",
        englishName: "Oscar Wang",
        studentID: "YB976565",
        status: "學會會員",
    },
    {
        chineseName: "冯丽柔",
        englishName: "fenglirou",
        studentID: "MB950001",
        status: "學會會員",
    },
    {
        chineseName: "陳汝樺",
        englishName: "Chan U Wa",
        studentID: "BB802746",
        status: "學會會員",
    },
    {
        chineseName: "蔣智勇",
        englishName: "Cheong Chi Iong",
        studentID: "AB915612",
        status: "學會會員",
    },
    {
        chineseName: "黃啓華",
        englishName: "Vong Kai Wa",
        studentID: "AB815863",
        status: "學會會員",
    },
    {
        chineseName: "苏孟晗",
        englishName: "Marvin",
        studentID: "AB917559",
        status: "學會會員",
    },
    {
        chineseName: "陈鸿儒",
        englishName: "chen hongru",
        studentID: "AB917881",
        status: "學會會員",
    },
    {
        chineseName: "張卓生",
        englishName: "CHEONG CHEOK SANG",
        studentID: "BB902049",
        status: "學會會員",
    },
    {
        chineseName: "李致远",
        englishName: "LEI CHI UN",
        studentID: "DB927063",
        status: "學會會員",
    },
    {
        chineseName: "马懿珈",
        englishName: "Ma YjJia",
        studentID: "DB828012",
        status: "學會會員",
    },
    {
        chineseName: "蔡國鑫",
        englishName: "Tdai Kuo Hsin",
        studentID: "SB919100",
        status: "學會會員",
    },
    {
        chineseName: "张玮泽",
        englishName: "ZHANG WEI ZE",
        studentID: "DB927910",
        status: "學會會員",
    },
    {
        chineseName: "李松岳",
        englishName: "Li SongYue",
        studentID: "BB901278",
        status: "學會會員",
    },
    {
        chineseName: "刘斯行",
        englishName: "Liu Sihang",
        studentID: "SB923101",
        status: "學會會員",
    },
    {
        chineseName: "林嘉慧",
        englishName: "LIN JIA HUI",
        studentID: "SB923122",
        status: "學會會員",
    },
    {
        chineseName: "勞家輝",
        englishName: "LOU KA FAI",
        studentID: "DB926464",
        status: "學會會員",
    },
    {
        chineseName: "張月麗",
        englishName: "CHEONGUT LAI",
        studentID: "SB922701",
        status: "學會會員",
    },
    {
        chineseName: "李嘉棟",
        englishName: "Siro",
        studentID: "AB916248",
        status: "學會會員",
    },
    {
        chineseName: "张文宇",
        englishName: "Lukas",
        studentID: "DB928262",
        status: "學會會員",
    },
    {
        chineseName: "李旭",
        englishName: "LI XU",
        studentID: "SB923252",
        status: "學會會員",
    },
    {
        chineseName: "陳永祺",
        englishName: "CHAN Wing Ki",
        studentID: "DB925913",
        status: "學會會員",
    },
    {
        chineseName: "羅志輝",
        englishName: "LO CHI FAI",
        studentID: "BB902465",
        status: "學會會員",
    },
    {
        chineseName: "鄭子聰",
        englishName: "Chiang Chi Chong ",
        studentID: "BB900500",
        status: "學會會員",
    },
    {
        chineseName: "唐海翔",
        englishName: "TANG HAIXIANG",
        studentID: "DB925970",
        status: "學會會員",
    },
    {
        chineseName: "朱銘琨",
        englishName: "chu ming kun",
        studentID: "SB620162",
        status: "學會會員",
    },
    {
        chineseName: "王正浩",
        englishName: "Peter",
        studentID: "BB905752",
        status: "學會會員",
    },
    {
        chineseName: "吳孟璋",
        englishName: "WU MENG CHANG ",
        studentID: "SB921855",
        status: "學會會員",
    },
    {
        chineseName: "廖贺龙",
        englishName: "LIO HO LONG",
        studentID: "BB904061",
        status: "學會會員",
    },
    {
        chineseName: "梁綺玲",
        englishName: "LEONG I LENG",
        studentID: "SB821623",
        status: "學會會員",
    },
    {
        chineseName: "黃峻彬",
        englishName: "Pascal Wong",
        studentID: "DB926940",
        status: "學會會員",
    },
    {
        chineseName: "勞梓華",
        englishName: "LAO ZI HUA",
        studentID: "DB926521",
        status: "學會會員",
    },
    {
        chineseName: "蔡昊書",
        englishName: "TSAI HAO SHU ",
        studentID: "DB926654",
        status: "學會會員",
    },
    {
        chineseName: "鄒錦樺",
        englishName: "None",
        studentID: "DB82666",
        status: "學會會員",
    },
    {
        chineseName: "陳遠亮",
        englishName: "None",
        studentID: "DB82575",
        status: "學會會員",
    },
    {
        chineseName: "廖俊裕",
        englishName: "None",
        studentID: "DB82661",
        status: "學會會員",
    },
    {
        chineseName: "郭陈鸿",
        englishName: "None",
        studentID: "DB825187",
        status: "學會會員",
    },
    {
        chineseName: "吳俊華",
        englishName: "None",
        studentID: "DB826546",
        status: "學會會員",
    },
    {
        chineseName: "梁頌軒",
        englishName: "None",
        studentID: "DB825530",
        status: "學會會員",
    },
    {
        chineseName: "王怿逍",
        englishName: "None",
        studentID: "DB827534",
        status: "學會會員",
    },
    {
        chineseName: "莫康禮",
        englishName: "None",
        studentID: "DB82501",
        status: "學會會員",
    },
    {
        chineseName: "Tong Weng Hou",
        englishName: "None",
        studentID: "MB85407",
        status: "學會會員",
    },
    {
        chineseName: "李光宇",
        englishName: "None",
        studentID: "DB827751",
        status: "學會會員",
    },
    {
        chineseName: "房冠钰",
        englishName: "None",
        studentID: "HB81176",
        status: "學會會員",
    },
    {
        chineseName: "吳嘉銘",
        englishName: "None",
        studentID: "SB819958",
        status: "學會會員",
    },
    {
        chineseName: "馮榮晉",
        englishName: "None",
        studentID: "SB82055",
        status: "學會會員",
    },
    {
        chineseName: "陳偉",
        englishName: "None",
        studentID: "DB82601",
        status: "學會會員",
    },
    {
        chineseName: "曾曦霆",
        englishName: "None",
        studentID: "SB820807",
        status: "學會會員",
    },
    {
        chineseName: "谢青蒲",
        englishName: "None",
        studentID: "BB80550",
        status: "學會會員",
    },
    {
        chineseName: "梁靜怡",
        englishName: "None",
        studentID: "DB826443",
        status: "學會會員",
    },
    {
        chineseName: "孫婷",
        englishName: "None",
        studentID: "HB810977",
        status: "學會會員",
    },
    {
        chineseName: "张丁洋",
        englishName: "None",
        studentID: "BB806424",
        status: "學會會員",
    },
    {
        chineseName: "王锦涛",
        englishName: "None",
        studentID: "DB82721",
        status: "學會會員",
    },
    {
        chineseName: "徐晶菁",
        englishName: "None",
        studentID: "DB825910",
        status: "學會會員",
    },
    {
        chineseName: "陈宝如",
        englishName: "None",
        studentID: "SB823620",
        status: "學會會員",
    },
    {
        chineseName: "馮捷康",
        englishName: "None",
        studentID: "DB826461",
        status: "學會會員",
    },
    {
        chineseName: "黎銳成",
        englishName: "None",
        studentID: "BB804562",
        status: "學會會員",
    },
    {
        chineseName: "高天舒",
        englishName: "None",
        studentID: "SB824132",
        status: "學會會員",
    },
    {
        chineseName: "俞龙娇",
        englishName: "None",
        studentID: "SB82392",
        status: "學會會員",
    },
    {
        chineseName: "陈宛青",
        englishName: "None",
        studentID: "BB806623",
        status: "學會會員",
    },
    {
        chineseName: "邓佳蕙",
        englishName: "None",
        studentID: "SB82399",
        status: "學會會員",
    },
    {
        chineseName: "李俊星",
        englishName: "None",
        studentID: "SB819671",
        status: "學會會員",
    },
    {
        chineseName: "吴国成",
        englishName: "None",
        studentID: "DB626918",
        status: "學會會員",
    },
    {
        chineseName: "卓琳",
        englishName: "None",
        studentID: "CB82429",
        status: "學會會員",
    },
    {
        chineseName: "张羽惟",
        englishName: "None",
        studentID: "DB82746",
        status: "學會會員",
    },
    {
        chineseName: "杨博涵",
        englishName: "None",
        studentID: "BB805786",
        status: "學會會員",
    },
    {
        chineseName: "黄雅琪",
        englishName: "None",
        studentID: "BB803423",
        status: "學會會員",
    },
    {
        chineseName: "陶一玮",
        englishName: "None",
        studentID: "DB827884",
        status: "學會會員",
    },
    {
        chineseName: "徐睿晗",
        englishName: "None",
        studentID: "BB805795",
        status: "學會會員",
    },
    {
        chineseName: "郑玉龙",
        englishName: "None",
        studentID: "SB82118",
        status: "學會會員",
    },
    {
        chineseName: "胡忠宏",
        englishName: "None",
        studentID: "AB815254",
        status: "學會會員",
    },
    {
        chineseName: "施星宇",
        englishName: "None",
        studentID: "BB806511",
        status: "學會會員",
    },
    {
        chineseName: "鄒卓信",
        englishName: "None",
        studentID: "DB82607",
        status: "學會會員",
    },
    {
        chineseName: "李澤宏",
        englishName: "None",
        studentID: "DB82560",
        status: "學會會員",
    },
    {
        chineseName: "殷希汶",
        englishName: "None",
        studentID: "DB825169",
        status: "學會會員",
    },
    {
        chineseName: "刘锐鸣",
        englishName: "None",
        studentID: "DB827962",
        status: "學會會員",
    },
    {
        chineseName: "李志燊",
        englishName: "None",
        studentID: "CB829263",
        status: "學會會員",
    },
    {
        chineseName: "Samy",
        englishName: "None",
        studentID: "BB804306",
        status: "學會會員",
    },
    {
        chineseName: "陳曉琳",
        englishName: "None",
        studentID: "BB803487",
        status: "學會會員",
    },
    {
        chineseName: "韓智浩",
        englishName: "None",
        studentID: "DB826832",
        status: "學會會員",
    },
    {
        chineseName: "李锦龙",
        englishName: "None",
        studentID: "DB825784",
        status: "學會會員",
    },
    {
        chineseName: "赵剑辉",
        englishName: "None",
        studentID: "SB721732",
        status: "學會會員",
    },
    {
        chineseName: "邱浚豪",
        englishName: "None",
        studentID: "DB825642",
        status: "學會會員",
    },
    {
        chineseName: "盧有仔",
        englishName: "None",
        studentID: "DB825036",
        status: "學會會員",
    },
    {
        chineseName: "俞沛泉",
        englishName: "None",
        studentID: "DB827413",
        status: "學會會員",
    },
    {
        chineseName: "薛嘉駿",
        englishName: "None",
        studentID: "DB826688",
        status: "學會會員",
    },
    {
        chineseName: "陳錦煇",
        englishName: "None",
        studentID: "DB626679",
        status: "學會會員",
    },
    {
        chineseName: "黃加禧",
        englishName: "None",
        studentID: "DB825045",
        status: "學會會員",
    },
    {
        chineseName: "李偉康",
        englishName: "None",
        studentID: "DB82557",
        status: "學會會員",
    },
    {
        chineseName: "肖嵐",
        englishName: "None",
        studentID: "AB817812",
        status: "學會會員",
    },
    {
        chineseName: "张广越",
        englishName: "None",
        studentID: "DB827326",
        status: "學會會員",
    },
    {
        chineseName: "郭宝泓",
        englishName: "None",
        studentID: "BB805587",
        status: "學會會員",
    },
    {
        chineseName: "柯添丰",
        englishName: "None",
        studentID: "DB827612",
        status: "學會會員",
    },
    {
        chineseName: "普弋洋",
        englishName: "None",
        studentID: "AB817622",
        status: "學會會員",
    },
    {
        chineseName: "柯竣淼",
        englishName: "None",
        studentID: "BB805170",
        status: "學會會員",
    },
    {
        chineseName: "谢雨辰",
        englishName: "None",
        studentID: "DB827371",
        status: "學會會員",
    },
    {
        chineseName: "羅羿",
        englishName: "None",
        studentID: "BB807005",
        status: "學會會員",
    },
    {
        chineseName: "胡俊杰",
        englishName: "None",
        studentID: "BB80187",
        status: "學會會員",
    },
    {
        chineseName: "张雨童",
        englishName: "None",
        studentID: "BB80620",
        status: "學會會員",
    },
    {
        chineseName: "樂佾欣",
        englishName: "None",
        studentID: "BB807708",
        status: "學會會員",
    },
    {
        chineseName: "曾宇楷",
        englishName: "None",
        studentID: "DB826347",
        status: "學會會員",
    },
    {
        chineseName: "余林傑",
        englishName: "None",
        studentID: "DB825748",
        status: "學會會員",
    },
    {
        chineseName: "潘立賢",
        englishName: "None",
        studentID: "DB826470",
        status: "學會會員",
    },
    {
        chineseName: "梁曉城",
        englishName: "None",
        studentID: "SB820379",
        status: "學會會員",
    },
    {
        chineseName: "蕭洛文",
        englishName: "None",
        studentID: "BB80186",
        status: "學會會員",
    },
    {
        chineseName: "刘峥",
        englishName: "None",
        studentID: "DB827706",
        status: "學會會員",
    },
    {
        chineseName: "吴春萱",
        englishName: "None",
        studentID: "BB805635",
        status: "學會會員",
    },
    {
        chineseName: "经文宇",
        englishName: "None",
        studentID: "MB856250",
        status: "學會會員",
    },
    {
        chineseName: "歐陽坤瑜",
        englishName: "None",
        studentID: "DB626432",
        status: "學會會員",
    },
    {
        chineseName: "李肇淇",
        englishName: "None",
        studentID: "DB826537",
        status: "學會會員",
    },
    {
        chineseName: "鄭偉星",
        englishName: "None",
        studentID: "DB825150",
        status: "學會會員",
    },
    {
        chineseName: "吳智濤",
        englishName: "None",
        studentID: "DB82664",
        status: "學會會員",
    },
    {
        chineseName: "曾艷蘭",
        englishName: "None",
        studentID: "BB803164",
        status: "學會會員",
    },
    {
        chineseName: "陳傲雷",
        englishName: "None",
        studentID: "DB82797",
        status: "學會會員",
    },
    {
        chineseName: "歐芷晴",
        englishName: "None",
        studentID: "AB816556",
        status: "學會會員",
    },
    {
        chineseName: "葉偉添",
        englishName: "None",
        studentID: "DB82561",
        status: "學會會員",
    },
    {
        chineseName: "區偉漢",
        englishName: "None",
        studentID: "BB801103",
        status: "學會會員",
    },
    {
        chineseName: "許嘉盛",
        englishName: "None",
        studentID: "DB825443",
        status: "學會會員",
    },
    {
        chineseName: "唐子穎",
        englishName: "None",
        studentID: "DB826299",
        status: "學會會員",
    },
    {
        chineseName: "吉詠琪",
        englishName: "None",
        studentID: "SB620931",
        status: "學會會員",
    },
    {
        chineseName: "周婼瑤",
        englishName: "None",
        studentID: "SB719129",
        status: "學會會員",
    },
    {
        chineseName: "鄧子笙",
        englishName: "None",
        studentID: "SB82254",
        status: "學會會員",
    },
    {
        chineseName: "李依倫",
        englishName: "None",
        studentID: "SB824723",
        status: "學會會員",
    },
    {
        chineseName: "顏定瀚",
        englishName: "None",
        studentID: "SB824711",
        status: "學會會員",
    },
    {
        chineseName: "姚逸帆",
        englishName: "None",
        studentID: "DB827097",
        status: "學會會員",
    },
    {
        chineseName: "Wong Wang Yip",
        englishName: "None",
        studentID: "BB606178",
        status: "學會會員",
    },
    {
        chineseName: "黃啟華",
        englishName: "None",
        studentID: "AB815863",
        status: "學會會員",
    },
    {
        chineseName: "區廣浩",
        englishName: "None",
        studentID: "DB726115",
        status: "學會會員",
    },
    {
        chineseName: "歐廣豪",
        englishName: "None",
        studentID: "DB826120",
        status: "學會會員",
    },
    {
        chineseName: "王和平",
        englishName: "None",
        studentID: "DB826413",
        status: "學會會員",
    },
    {
        chineseName: "邱天美",
        englishName: "None",
        studentID: "12611492",
        status: "學會會員",
    },
    {
        chineseName: "陳浩謙",
        englishName: "None",
        studentID: "DB62610",
        status: "學會會員",
    },
    {
        chineseName: "龔文龍",
        englishName: "None",
        studentID: "DB62531",
        status: "學會會員",
    },
    {
        chineseName: "蘇靖榆",
        englishName: "None",
        studentID: "SB822744",
        status: "學會會員",
    },
    {
        chineseName: "黃子健",
        englishName: "None",
        studentID: "DB825217",
        status: "學會會員",
    },
    {
        chineseName: "蘇慧根",
        englishName: "None",
        studentID: "DB826519",
        status: "學會會員",
    },
    {
        chineseName: "马景坤",
        englishName: "None",
        studentID: "DB82779",
        status: "學會會員",
    },
    {
        chineseName: "許顯宏",
        englishName: "None",
        studentID: "SB821889",
        status: "學會會員",
    },
    {
        chineseName: "戴曉盈",
        englishName: "None",
        studentID: "SB822382",
        status: "學會會員",
    },
    {
        chineseName: "殷帅",
        englishName: "None",
        studentID: "AB818541",
        status: "學會會員",
    },
    {
        chineseName: "刘翠霞",
        englishName: "None",
        studentID: "DB719982",
        status: "學會會員",
    },
    {
        chineseName: "劉俊燁",
        englishName: "None",
        studentID: "DB82663",
        status: "學會會員",
    },
    {
        chineseName: "尹熙琼",
        englishName: "None",
        studentID: "DB827383",
        status: "學會會員",
    },
    {
        chineseName: "钟雨轩",
        englishName: "None",
        studentID: "DB82708",
        status: "學會會員",
    },
    {
        chineseName: "FRANK",
        englishName: "None",
        studentID: "DB825766",
        status: "學會會員",
    },
    {
        chineseName: "李昊阳",
        englishName: "None",
        studentID: "DB827525",
        status: "學會會員",
    },
    {
        chineseName: "廖嘉榮",
        englishName: "None",
        studentID: "DB825253",
        status: "學會會員",
    },
    {
        chineseName: "劉偉斌",
        englishName: "None",
        studentID: "DB825235",
        status: "學會會員",
    },
    {
        chineseName: "董士涛",
        englishName: "None",
        studentID: "DB827193",
        status: "學會會員",
    },
    {
        chineseName: "李紫晴",
        englishName: "None",
        studentID: "DB825832",
        status: "學會會員",
    },
    {
        chineseName: "張家輝",
        englishName: "None",
        studentID: "DB826310",
        status: "學會會員",
    },
    {
        chineseName: "梁子堅",
        englishName: "None",
        studentID: "DB826006",
        status: "學會會員",
    },
    {
        chineseName: "何嘉麗",
        englishName: "None",
        studentID: "DB82650",
        status: "學會會員",
    },
    {
        chineseName: "楊明康",
        englishName: "None",
        studentID: "DB825292",
        status: "學會會員",
    },
    {
        chineseName: "梁銘暉",
        englishName: "None",
        studentID: "DB82632",
        status: "學會會員",
    },
    {
        chineseName: "陳亮延",
        englishName: "None",
        studentID: "DB826489",
        status: "學會會員",
    },
    {
        chineseName: "梁嘉舜",
        englishName: "None",
        studentID: "BB80524",
        status: "學會會員",
    },
    {
        chineseName: "梁永揚",
        englishName: "None",
        studentID: "DB825111",
        status: "學會會員",
    },
    {
        chineseName: "Lansang Joao Miguel",
        englishName: "None",
        studentID: "DB825567",
        status: "學會會員",
    },
    {
        chineseName: "黃志浩",
        englishName: "None",
        studentID: "DB825313",
        status: "學會會員",
    },
    {
        chineseName: "林偉俊",
        englishName: "None",
        studentID: "DB825301",
        status: "學會會員",
    },
    {
        chineseName: "鄺煒晉",
        englishName: "None",
        studentID: "DB826887",
        status: "學會會員",
    },
    {
        chineseName: "陳天奇",
        englishName: "None",
        studentID: "DB825711",
        status: "學會會員",
    },
    {
        chineseName: "林海晴",
        englishName: "None",
        studentID: "BB801112",
        status: "學會會員",
    },
    {
        chineseName: "许荣震",
        englishName: "None",
        studentID: "DB826621",
        status: "學會會員",
    },
    {
        chineseName: "陈雪飞",
        englishName: "None",
        studentID: "DB827344",
        status: "學會會員",
    },
    {
        chineseName: "王宇豪",
        englishName: "None",
        studentID: "DB62632",
        status: "學會會員",
    },
    {
        chineseName: "黎振乾",
        englishName: "None",
        studentID: "P1802842",
        status: "學會會員",
    },
    {
        chineseName: "张晋曦",
        englishName: "None",
        studentID: "DB727378",
        status: "學會會員",
    },
    {
        chineseName: "唐康懷",
        englishName: "None",
        studentID: "DB825956",
        status: "學會會員",
    },
    {
        chineseName: "李家礽",
        englishName: "None",
        studentID: "DB826338",
        status: "學會會員",
    },
    {
        chineseName: "牛思齐",
        englishName: "None",
        studentID: "BB806641",
        status: "學會會員",
    },
    {
        chineseName: "黃曉晴",
        englishName: "None",
        studentID: "DB826090",
        status: "學會會員",
    },
    {
        chineseName: "KC",
        englishName: "None",
        studentID: "DB525221",
        status: "學會會員",
    },
    {
        chineseName: "曾曉彤",
        englishName: "None",
        studentID: "SB721412",
        status: "學會會員",
    },
    {
        chineseName: "陈少洲",
        englishName: "None",
        studentID: "BB801311",
        status: "學會會員",
    },
    {
        chineseName: "陈少洲",
        englishName: "None",
        studentID: "BB801311",
        status: "學會會員",
    },
    {
        chineseName: "HO Ka Chon",
        englishName: "None",
        studentID: "DB525221",
        status: "學會會員",
    },
    {
        chineseName: "CHOI CHEONG CHUN",
        englishName: "None",
        studentID: "BB401370",
        status: "學會會員",
    },
    {
        chineseName: "范志勇",
        englishName: "None",
        studentID: "BB400970",
        status: "學會會員",
    },
    {
        chineseName: "ng ka chon",
        englishName: "None",
        studentID: "DB326714",
        status: "學會會員",
    },
    {
        chineseName: "劉倩姮",
        englishName: "None",
        studentID: "DB325678",
        status: "學會會員",
    },
    {
        chineseName: "曾沁玮",
        englishName: "None",
        studentID: "SB523492",
        status: "學會會員",
    },
    {
        chineseName: "鄭毅峰",
        englishName: "None",
        studentID: "DB228202",
        status: "學會會員",
    },
    {
        chineseName: "CHOI CHEONG CHUN",
        englishName: "None",
        studentID: "BB401370",
        status: "學會會員",
    },
    {
        chineseName: "陳敬仁",
        englishName: "None",
        studentID: "DB526610",
        status: "學會會員",
    },
    {
        chineseName: "李宗儒",
        englishName: "None",
        studentID: "BB401663",
        status: "學會會員",
    },
    {
        chineseName: "何健聪",
        englishName: "None",
        studentID: "DB525791",
        status: "學會會員",
    },
    {
        chineseName: "He lei",
        englishName: "None",
        studentID: "AB617509",
        status: "學會會員",
    },
    {
        chineseName: "盧曉樺",
        englishName: "None",
        studentID: "SB619844",
        status: "學會會員",
    },
    {
        chineseName: "陳柔詩",
        englishName: "None",
        studentID: "SB619132",
        status: "學會會員",
    },
    {
        chineseName: "陳家欣",
        englishName: "None",
        studentID: "AB615131",
        status: "學會會員",
    },
    {
        chineseName: "許嘉俊",
        englishName: "None",
        studentID: "DB626689",
        status: "學會會員",
    },
    {
        chineseName: "楊潮葦",
        englishName: "None",
        studentID: "DB62510",
        status: "學會會員",
    },
    {
        chineseName: "Chris",
        englishName: "None",
        studentID: "BB602481",
        status: "學會會員",
    },
    {
        chineseName: "麥嘉文",
        englishName: "None",
        studentID: "DB626453",
        status: "學會會員",
    },
    {
        chineseName: "梁仲恩",
        englishName: "None",
        studentID: "DB626281",
        status: "學會會員",
    },
    {
        chineseName: "吳嘉輝",
        englishName: "None",
        studentID: "DB626981",
        status: "學會會員",
    },
    {
        chineseName: "周銘鴻",
        englishName: "None",
        studentID: "DB625616",
        status: "學會會員",
    },
    {
        chineseName: "Raul Chang Monteiro",
        englishName: "None",
        studentID: "LB61393",
        status: "學會會員",
    },
    {
        chineseName: "劉劍邦",
        englishName: "None",
        studentID: "AB61614",
        status: "學會會員",
    },
    {
        chineseName: "葉桐",
        englishName: "None",
        studentID: "DB62578",
        status: "學會會員",
    },
    {
        chineseName: "叶凌伟",
        englishName: "None",
        studentID: "SB623525",
        status: "學會會員",
    },
    {
        chineseName: "鄒家華",
        englishName: "None",
        studentID: "SB522239",
        status: "學會會員",
    },
    {
        chineseName: "陳冠華",
        englishName: "None",
        studentID: "DB627173",
        status: "學會會員",
    },
    {
        chineseName: "林業銘",
        englishName: "None",
        studentID: "DB626909",
        status: "學會會員",
    },
    {
        chineseName: "陳錦燊",
        englishName: "None",
        studentID: "DB526656",
        status: "學會會員",
    },
    {
        chineseName: "蔡志恆",
        englishName: "None",
        studentID: "DB625595",
        status: "學會會員",
    },
    {
        chineseName: "陈子昕",
        englishName: "None",
        studentID: "AB618714",
        status: "學會會員",
    },
    {
        chineseName: "陈子昕",
        englishName: "None",
        studentID: "AB618714",
        status: "學會會員",
    },
    {
        chineseName: "駱志穎",
        englishName: "None",
        studentID: "DB42599",
        status: "學會會員",
    },
    {
        chineseName: "梁聞顥",
        englishName: "None",
        studentID: "SB619636",
        status: "學會會員",
    },
    {
        chineseName: "戴俊傑",
        englishName: "None",
        studentID: "DB62822601",
        status: "學會會員",
    },
    {
        chineseName: "戴俊傑",
        englishName: "None",
        studentID: "DB62822601",
        status: "學會會員",
    },
    {
        chineseName: "鄭穎濠",
        englishName: "None",
        studentID: "DB625091",
        status: "學會會員",
    },
    {
        chineseName: "鄭穎濠",
        englishName: "None",
        studentID: "DB625091",
        status: "學會會員",
    },
    {
        chineseName: "Ng Weng nin",
        englishName: "None",
        studentID: "BB603527",
        status: "學會會員",
    },
    {
        chineseName: "Lei chon kit",
        englishName: "None",
        studentID: "BB602575",
        status: "學會會員",
    },
    {
        chineseName: "Cheong Chi Kit",
        englishName: "None",
        studentID: "SB619123",
        status: "學會會員",
    },
    {
        chineseName: "Lei chon kit",
        englishName: "None",
        studentID: "BB602575",
        status: "學會會員",
    },
    {
        chineseName: "蔡志恆",
        englishName: "None",
        studentID: "DB625595",
        status: "學會會員",
    },
    {
        chineseName: "张柏良",
        englishName: "None",
        studentID: "BB50605",
        status: "學會會員",
    },
    {
        chineseName: "羅明煒",
        englishName: "None",
        studentID: "BB501213",
        status: "學會會員",
    },
    {
        chineseName: "陳天俊",
        englishName: "None",
        studentID: "DB42596",
        status: "學會會員",
    },
    {
        chineseName: "林志遠",
        englishName: "None",
        studentID: "AB616451",
        status: "學會會員",
    },
    {
        chineseName: "陳頴彤",
        englishName: "None",
        studentID: "BB502430",
        status: "學會會員",
    },
    {
        chineseName: "羅毅楓",
        englishName: "None",
        studentID: "BB60154",
        status: "學會會員",
    },
    {
        chineseName: "MD SHAKHAWAT HOSSAIN",
        englishName: "None",
        studentID: "DB526882",
        status: "學會會員",
    },
    {
        chineseName: "何志健",
        englishName: "None",
        studentID: "BB60193",
        status: "學會會員",
    },
    {
        chineseName: "Chan Shu Hei",
        englishName: "None",
        studentID: "DB52697",
        status: "學會會員",
    },
    {
        chineseName: "鍾文峻",
        englishName: "None",
        studentID: "DB626384",
        status: "學會會員",
    },
    {
        chineseName: "趙祈康",
        englishName: "None",
        studentID: "DB526599",
        status: "學會會員",
    },
    {
        chineseName: "顧培生",
        englishName: "None",
        studentID: "DB62627",
        status: "學會會員",
    },
    {
        chineseName: "梅達成",
        englishName: "None",
        studentID: "BB602358",
        status: "學會會員",
    },
    {
        chineseName: "許達威",
        englishName: "None",
        studentID: "AB617080",
        status: "學會會員",
    },
    {
        chineseName: "Kiner",
        englishName: "None",
        studentID: "DB425816",
        status: "學會會員",
    },
    {
        chineseName: "莫桂源",
        englishName: "None",
        studentID: "DB625378",
        status: "學會會員",
    },
    {
        chineseName: "黃敏新",
        englishName: "None",
        studentID: "DB625218",
        status: "學會會員",
    },
    {
        chineseName: "曾梓烔",
        englishName: "None",
        studentID: "DB627191",
        status: "學會會員",
    },
    {
        chineseName: "Liang Jinxuan",
        englishName: "None",
        studentID: "DB625254",
        status: "學會會員",
    },
    {
        chineseName: "趙展瑭",
        englishName: "None",
        studentID: "DB626242",
        status: "學會會員",
    },
    {
        chineseName: "林秉逸",
        englishName: "None",
        studentID: "DB625806",
        status: "學會會員",
    },
    {
        chineseName: "伍劍豪",
        englishName: "None",
        studentID: "DB62536",
        status: "學會會員",
    },
    {
        chineseName: "鄭詠稀",
        englishName: "None",
        studentID: "DB625417",
        status: "學會會員",
    },
    {
        chineseName: "葉柏麟",
        englishName: "None",
        studentID: "DB625471",
        status: "學會會員",
    },
    {
        chineseName: "石子峰",
        englishName: "None",
        studentID: "DB626149",
        status: "學會會員",
    },
    {
        chineseName: "林嘉俊",
        englishName: "None",
        studentID: "DB626167",
        status: "學會會員",
    },
    {
        chineseName: "歐嘉捷",
        englishName: "None",
        studentID: "DB626414",
        status: "學會會員",
    },
    {
        chineseName: "馬曉君",
        englishName: "None",
        studentID: "DB625661",
        status: "學會會員",
    },
    {
        chineseName: "陈曦明",
        englishName: "None",
        studentID: "DB625815",
        status: "學會會員",
    },
    {
        chineseName: "李俊飞",
        englishName: "None",
        studentID: "DB626972",
        status: "學會會員",
    },
    {
        chineseName: "趙雲龍",
        englishName: "None",
        studentID: "DB62552",
        status: "學會會員",
    },
    {
        chineseName: "何詩琦",
        englishName: "None",
        studentID: "DB626499",
        status: "學會會員",
    },
    {
        chineseName: "陳穎鴻",
        englishName: "None",
        studentID: "DB625767",
        status: "學會會員",
    },
    {
        chineseName: "梁力恒",
        englishName: "None",
        studentID: "DB626233",
        status: "學會會員",
    },
    {
        chineseName: "Jim Pong",
        englishName: "None",
        studentID: "BB60251",
        status: "學會會員",
    },
    {
        chineseName: "Jim Pong",
        englishName: "None",
        studentID: "BB60251",
        status: "學會會員",
    },
    {
        chineseName: "胡文鋒",
        englishName: "None",
        studentID: "DB626091",
        status: "學會會員",
    },
    {
        chineseName: "梁曉殷",
        englishName: "None",
        studentID: "BB601976",
        status: "學會會員",
    },
    {
        chineseName: "馮智謙",
        englishName: "None",
        studentID: "BB302848",
        status: "學會會員",
    },
    {
        chineseName: "阮君亭",
        englishName: "None",
        studentID: "BB501831",
        status: "學會會員",
    },
    {
        chineseName: "Lei Cheok Leng",
        englishName: "None",
        studentID: "DB72639",
        status: "學會會員",
    },
    {
        chineseName: "羅寶琪",
        englishName: "None",
        studentID: "DB72538",
        status: "學會會員",
    },
    {
        chineseName: "張晉杰",
        englishName: "None",
        studentID: "DB725875",
        status: "學會會員",
    },
    {
        chineseName: "馮嘉咏",
        englishName: "None",
        studentID: "DB725914",
        status: "學會會員",
    },
    {
        chineseName: "周志傑",
        englishName: "None",
        studentID: "DB725694",
        status: "學會會員",
    },
    {
        chineseName: "羅寶琪",
        englishName: "None",
        studentID: "DB725383",
        status: "學會會員",
    },
    {
        chineseName: "鄭文波",
        englishName: "None",
        studentID: "DB725962",
        status: "學會會員",
    },
    {
        chineseName: "周志傑",
        englishName: "None",
        studentID: "DB725694",
        status: "學會會員",
    },
    {
        chineseName: "陳嘉榮",
        englishName: "None",
        studentID: "DB726202",
        status: "學會會員",
    },
    {
        chineseName: "陸晉榮",
        englishName: "None",
        studentID: "DB726058",
        status: "學會會員",
    },
    {
        chineseName: "LIANG JIAYING (梁嘉盈)",
        englishName: "None",
        studentID: "DB725401",
        status: "學會會員",
    },
    {
        chineseName: "Maria Lam (林海晴)",
        englishName: "None",
        studentID: "LB713179",
        status: "學會會員",
    },
    {
        chineseName: "古樹樺",
        englishName: "None",
        studentID: "DB72574",
        status: "學會會員",
    },
    {
        chineseName: "薛浩然",
        englishName: "None",
        studentID: "DB726456",
        status: "學會會員",
    },
    {
        chineseName: "黃濠華",
        englishName: "None",
        studentID: "DB726094",
        status: "學會會員",
    },
    {
        chineseName: "伍仲鈜",
        englishName: "None",
        studentID: "BB701571",
        status: "學會會員",
    },
    {
        chineseName: "陈立杰",
        englishName: "None",
        studentID: "BB702988",
        status: "學會會員",
    },
    {
        chineseName: "陈江铃",
        englishName: "None",
        studentID: "BB701553",
        status: "學會會員",
    },
    {
        chineseName: "趙劍輝",
        englishName: "None",
        studentID: "SB721732",
        status: "學會會員",
    },
    {
        chineseName: "巫嘉莉",
        englishName: "None",
        studentID: "DB725278",
        status: "學會會員",
    },
    {
        chineseName: "苏宏益",
        englishName: "None",
        studentID: "CB729061",
        status: "學會會員",
    },
    {
        chineseName: "李卓鈴",
        englishName: "None",
        studentID: "DB72639",
        status: "學會會員",
    },
    {
        chineseName: "趙銘熙",
        englishName: "None",
        studentID: "BB700499",
        status: "學會會員",
    },
    {
        chineseName: "楊梓楓",
        englishName: "None",
        studentID: "DB72505",
        status: "學會會員",
    },
    {
        chineseName: "李志鵬",
        englishName: "None",
        studentID: "SB721153",
        status: "學會會員",
    },
    {
        chineseName: "趙洋頡",
        englishName: "None",
        studentID: "BB505772",
        status: "學會會員",
    },
    {
        chineseName: "張靖妍",
        englishName: "None",
        studentID: "HB410493",
        status: "學會會員",
    },
    {
        chineseName: "Wong Weng U (黃詠瑜)",
        englishName: "None",
        studentID: "DB725431",
        status: "學會會員",
    },
    {
        chineseName: "潘梓鍵",
        englishName: "None",
        studentID: "DB625577",
        status: "學會會員",
    },
    {
        chineseName: "歐陽海寧",
        englishName: "None",
        studentID: "SB72065",
        status: "學會會員",
    },
    {
        chineseName: "何國豪",
        englishName: "None",
        studentID: "DB72528",
        status: "學會副會長",
    },
    {
        chineseName: "何竣浠",
        englishName: "None",
        studentID: "DB62600",
        status: "學會會員",
    },
    {
        chineseName: "胡子洋",
        englishName: "None",
        studentID: "DB726779",
        status: "學會會員",
    },
    {
        chineseName: "黃正光",
        englishName: "None",
        studentID: "BB503609",
        status: "學會會員",
    },
    {
        chineseName: "陳承禧",
        englishName: "None",
        studentID: "DB726673",
        status: "學會會員",
    },
    {
        chineseName: "張力麒",
        englishName: "None",
        studentID: "DB726682",
        status: "學會會員",
    },
    {
        chineseName: "關燕玲",
        englishName: "None",
        studentID: "DB725269",
        status: "學會會員",
    },
    {
        chineseName: "陳駿傑",
        englishName: "None",
        studentID: "DB725839",
        status: "學會會員",
    },
    {
        chineseName: "Wiro Joshua Umacob Alegre",
        englishName: "None",
        studentID: "AB717264",
        status: "學會會員",
    },
    {
        chineseName: "黃家華",
        englishName: "None",
        studentID: "SB720916",
        status: "學會會員",
    },
    {
        chineseName: "黎俊銘",
        englishName: "None",
        studentID: "SB72042",
        status: "學會會員",
    },
    {
        chineseName: "溫凱晴",
        englishName: "None",
        studentID: "DB725250",
        status: "學會會員",
    },
    {
        chineseName: "李澳童",
        englishName: "None",
        studentID: "HB711573",
        status: "學會會員",
    },
    {
        chineseName: "陳民強",
        englishName: "None",
        studentID: "BB401862",
        status: "學會會員",
    },
    {
        chineseName: "范梓扬",
        englishName: "None",
        studentID: "DB727188",
        status: "學會會員",
    },
    {
        chineseName: "王琳鑫",
        englishName: "None",
        studentID: "HB61058",
        status: "學會會員",
    },
    {
        chineseName: "王琳鑫",
        englishName: "None",
        studentID: "HB61058",
        status: "學會會員",
    },
    {
        chineseName: "卓宏智",
        englishName: "None",
        studentID: "AB715592",
        status: "學會會員",
    },
    {
        chineseName: "羅寶琪",
        englishName: "None",
        studentID: "DB725383",
        status: "學會會員",
    },
    {
        chineseName: "梁俊恒",
        englishName: "None",
        studentID: "DB725763",
        status: "學會會員",
    },
    {
        chineseName: "周衍博",
        englishName: "None",
        studentID: "DB726664",
        status: "學會會員",
    },
    {
        chineseName: "林鳳妍",
        englishName: "None",
        studentID: "DB72506",
        status: "學會會員",
    },
    {
        chineseName: "程勝祺",
        englishName: "None",
        studentID: "DB726619",
        status: "學會會員",
    },
    {
        chineseName: "王曉山十",
        englishName: "None",
        studentID: "DB725371",
        status: "學會會員",
    },
    {
        chineseName: "Jasmineqy0 ",
        englishName: "None",
        studentID: "DB611408",
        status: "學會會員",
    },
    {
        chineseName: "曾偉凌",
        englishName: "None",
        studentID: "DB72579",
        status: "學會會員",
    },
    {
        chineseName: "鍾旭熙",
        englishName: "None",
        studentID: "DB72687",
        status: "學會會員",
    },
    {
        chineseName: "黄咏梅",
        englishName: "None",
        studentID: "DB725820",
        status: "學會會員",
    },
    {
        chineseName: "黃詠芯",
        englishName: "None",
        studentID: "HB710223",
        status: "學會會員",
    },
    {
        chineseName: "盧偉釗",
        englishName: "None",
        studentID: "DB726691",
        status: "學會會員",
    },
    {
        chineseName: "曠森",
        englishName: "None",
        studentID: "DB725042",
        status: "學會會員",
    },
    {
        chineseName: "林嘉亮",
        englishName: "None",
        studentID: "DB726410",
        status: "學會會員",
    },
    {
        chineseName: "CHAN KA CHON",
        englishName: "None",
        studentID: "DB726429",
        status: "學會會員",
    },
    {
        chineseName: "周家熙",
        englishName: "None",
        studentID: "SB723491",
        status: "學會會員",
    },
    {
        chineseName: "AXEL MUKWENA",
        englishName: "None",
        studentID: "DB727501",
        status: "學會會員",
    },
    {
        chineseName: "吳志誠",
        englishName: "None",
        studentID: "BB700082",
        status: "學會會員",
    },
    {
        chineseName: "MOYONGEN",
        englishName: "None",
        studentID: "BB501319",
        status: "學會會員",
    },
    {
        chineseName: "吳泳芬",
        englishName: "None",
        studentID: "SB519051",
        status: "學會會員",
    },
    {
        chineseName: "宋啟華",
        englishName: "None",
        studentID: "DB726447",
        status: "學會會員",
    },
    {
        chineseName: "Wan hoi cheng",
        englishName: "None",
        studentID: "DB725250",
        status: "學會會員",
    },
    {
        chineseName: "Fong ngai kan",
        englishName: "None",
        studentID: "BB603641",
        status: "學會會員",
    },
    {
        chineseName: "阮文杰",
        englishName: "None",
        studentID: "DB725603",
        status: "學會會員",
    },
    {
        chineseName: "劉建良",
        englishName: "None",
        studentID: "DB526704",
        status: "學會會員",
    },
    {
        chineseName: "李敏婷",
        englishName: "None",
        studentID: "HB51039",
        status: "學會會員",
    },
    {
        chineseName: "陳民祐",
        englishName: "None",
        studentID: "BB70497",
        status: "學會會員",
    },
    {
        chineseName: "劉若荑",
        englishName: "None",
        studentID: "AB717454",
        status: "學會會員",
    },
    {
        chineseName: "万梓源",
        englishName: "None",
        studentID: "DB627182",
        status: "學會會員",
    }
    ]
  }

function searchID(find_id,data){
  let regex = new RegExp(find_id,'i')
  let result = []
  let count = 0
  data.forEach(e=>{
    if(e.studentID.match(regex) && count < 10){
      result.push(e.studentID)
      count++
    }
  })
  console.log(result)
}

function matchID(find_id,data){
    find_id = find_id.toUpperCase()
    let result = false
    data.forEach(e => {
        if(find_id == e.studentID.toUpperCase()){
          result = e
        }
    })
    return result
}
var student_name_m = document.querySelector("#student_name_m")
var student_id_m = document.querySelector("#student_id_m")
var member_status_m = document.querySelector("#member_status_m")

//for keyup search
// document.querySelector("#student_id").addEventListener("keyup",(e)=>{
//   searchID(document.querySelector("#student_id").value,data.user)
// })

//for Enter search
document.querySelector("#submit_btn").addEventListener("click",(e)=>{
  result = matchID(document.querySelector("#student_id").value,data.user)
  if(result){
    document.querySelector("#message").style.display = "flex"
  }else{
    document.querySelector("#message").style.display = "none"
  }
  student_name_m.innerText = result.chineseName
  student_id_m.innerText = result.studentID
  member_status_m.innerText = result.status
})























